
% Generated by Chatgpt

function plotH5HierarchyTreeFinal7(filename)
% HDF5 hierarchy plot with vertical gaps, dataset info on right, larger boxes, and legend

info = h5info(filename);

% Storage
nodes = {};       
nodeType = {};    
datasetInfo = {}; 
levels = [];      
posY = [];        

childrenMap = containers.Map('KeyType','char','ValueType','any');

yCounter = 0;
vSpacing = 1.5;  % vertical gap between boxes

% Recursive traversal
function currentIndex = traverse(group, level, parentIndex)
    yCounter = yCounter + 1;
    nodes{end+1} = group.Name;
    nodeType{end+1} = 'group';
    datasetInfo{end+1} = '';
    levels(end+1) = level;
    posY(end+1) = -yCounter * vSpacing;
    currentIndex = length(nodes);

    % Map this node to parent
    if parentIndex > 0
        parentKey = num2str(parentIndex);
        if ~isKey(childrenMap, parentKey)
            childrenMap(parentKey) = [];
        end
        childrenMap(parentKey) = [childrenMap(parentKey), currentIndex];
    end

    % Add datasets
    for k = 1:length(group.Datasets)
        yCounter = yCounter + 1;
        nodes{end+1} = group.Datasets(k).Name;
        nodeType{end+1} = 'dataset';
        sz = group.Datasets(k).Dataspace.Size;
        if isempty(sz), sz = [1]; end
        datasetInfo{end+1} = sprintf('Size: %s\nType: %s', mat2str(sz), group.Datasets(k).Datatype.Type);
        levels(end+1) = level + 1;
        posY(end+1) = -yCounter * vSpacing;
        datasetIndex = length(nodes);

        % Map dataset to parent
        parentKey = num2str(currentIndex);
        if ~isKey(childrenMap, parentKey)
            childrenMap(parentKey) = [];
        end
        childrenMap(parentKey) = [childrenMap(parentKey), datasetIndex];
    end

    % Recurse into subgroups
    for k = 1:length(group.Groups)
        traverse(group.Groups(k), level + 1, currentIndex);
    end
end

traverse(info,0,0);

% Plot parameters
figure('Color','w','Name',['HDF5 Hierarchy: ', filename],'NumberTitle','off');
hold on
boxWidth = 3; boxHeight = 1;
xSpacing = 4;
fontBox = 12; fontInfo = 10;

% Draw boxes
for i = 1:length(nodes)
    x = levels(i) * xSpacing;
    y = posY(i);
    if strcmp(nodeType{i}, 'group')
        rectangle('Position',[x y boxWidth boxHeight],'FaceColor',[0.2 0.6 1],...
            'EdgeColor','k','LineWidth',1.5)
        text(x+boxWidth/2, y+boxHeight/2, nodes{i}, ...
            'HorizontalAlignment','center','VerticalAlignment','middle', ...
            'FontWeight','bold','FontSize',fontBox,'Color','w','Interpreter','none')
    else
        rectangle('Position',[x y boxWidth boxHeight],'FaceColor',[1 0.6 0.2],...
            'EdgeColor','k','LineWidth',1.5)
        text(x+boxWidth/2, y+boxHeight/2, nodes{i}, ...
            'HorizontalAlignment','center','VerticalAlignment','middle', ...
            'FontWeight','bold','FontSize',fontBox,'Color','k','Interpreter','none')

        % Dataset info outside the box (right side), two lines
        text(x+boxWidth + 0.2, y + boxHeight/2, datasetInfo{i}, ...
            'HorizontalAlignment','left','VerticalAlignment','middle', ...
            'FontSize',fontInfo,'Interpreter','none');
    end
end

% Draw connectors
parentKeys = keys(childrenMap);
for k = 1:length(parentKeys)
    parentIndex = str2double(parentKeys{k});
    parentLevel = levels(parentIndex);
    parentX = parentLevel * xSpacing + boxWidth;
    parentY = posY(parentIndex) + boxHeight/2;

    children = childrenMap(parentKeys{k});
    for c = children
        childX = levels(c) * xSpacing;
        childY = posY(c) + boxHeight/2;

        midX = parentX + 0.5;
        plot([parentX midX], [parentY parentY], 'k','LineWidth',1.5);
        plot([midX midX], [parentY childY], 'k','LineWidth',1.5);
        plot([midX childX], [childY childY], 'k','LineWidth',1.5);
    end
end

% Add legend (colored boxes with labels)
legendX = max(levels)*xSpacing + 2;
legendY = 0; % top of figure
legendBoxW = 1; legendBoxH = 0.5;

% Group/subgroup legend
rectangle('Position',[legendX legendY legendBoxW legendBoxH],'FaceColor',[0.2 0.6 1],...
    'EdgeColor','k','LineWidth',1.2)
text(legendX + legendBoxW + 0.2, legendY + legendBoxH/2, 'Group / Subgroup', ...
    'HorizontalAlignment','left','VerticalAlignment','middle','FontSize',fontInfo)

% Dataset legend
rectangle('Position',[legendX, legendY - legendBoxH - 0.2, legendBoxW, legendBoxH],...
    'FaceColor',[1 0.6 0.2],'EdgeColor','k','LineWidth',1.2)
text(legendX + legendBoxW + 0.2, legendY - legendBoxH/2 - 0.2, 'Dataset', ...
    'HorizontalAlignment','left','VerticalAlignment','middle','FontSize',fontInfo)

axis off
xlim([-1, max(levels)*xSpacing + 12]);
ylim([min(posY)-1 1]);
title(['HDF5 Hierarchy: ', filename],'FontWeight','bold','FontSize',14)
hold off
end